packages:
  - apps/**
  - packages/**
  - playground
  - '!**/dist/**'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  global: link:../../../Library/pnpm/global/5/node_modules/global
